// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OntarioParksExplorer.Api.Data;

#nullable disable

namespace OntarioParksExplorer.Api.Migrations
{
    [DbContext(typeof(ParksDbContext))]
    [Migration("20260328125227_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("OntarioParksExplorer.Api.Data.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("OntarioParksExplorer.Api.Data.Entities.Park", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsFeatured");

                    b.HasIndex("Name");

                    b.HasIndex("Region");

                    b.ToTable("Parks");
                });

            modelBuilder.Entity("OntarioParksExplorer.Api.Data.Entities.ParkActivity", b =>
                {
                    b.Property<int>("ParkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParkId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("ParkActivities");
                });

            modelBuilder.Entity("OntarioParksExplorer.Api.Data.Entities.ParkImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParkId");

                    b.ToTable("ParkImages");
                });

            modelBuilder.Entity("OntarioParksExplorer.Api.Data.Entities.ParkActivity", b =>
                {
                    b.HasOne("OntarioParksExplorer.Api.Data.Entities.Activity", "Activity")
                        .WithMany("ParkActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OntarioParksExplorer.Api.Data.Entities.Park", "Park")
                        .WithMany("ParkActivities")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Park");
                });

            modelBuilder.Entity("OntarioParksExplorer.Api.Data.Entities.ParkImage", b =>
                {
                    b.HasOne("OntarioParksExplorer.Api.Data.Entities.Park", "Park")
                        .WithMany("Images")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Park");
                });

            modelBuilder.Entity("OntarioParksExplorer.Api.Data.Entities.Activity", b =>
                {
                    b.Navigation("ParkActivities");
                });

            modelBuilder.Entity("OntarioParksExplorer.Api.Data.Entities.Park", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ParkActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
